version: 2.1

orbs:
  # Always take the latest version of the orb, this allows us to
  # run specs against Solidus supported versions only without the need
  # to change this configuration every time a Solidus version is released
  # or goes EOL.
  solidusio_extensions: solidusio/extensions@volatile


executors:
  sqlite-in-memory:
    docker:
      - image: circleci/ruby:2.5.6-node-browsers
        environment:
          RAILS_ENV: test
          DB: sqlite3
          DATABASE_URL: sqlite3::memory:?pool=1

jobs:
  run-specs-master:
    executor: sqlite-in-memory
    steps:
      - checkout
      - solidusio_extensions/test-branch:
          branch: master
      - store_test_results:
          path: test-results

  run-specs-2-9:
    executor: sqlite-in-memory
    steps:
      - checkout
      - solidusio_extensions/test-branch:
          branch: v2.9
      - store_test_results:
          path: test-results

  run-specs-2-8:
    executor: sqlite-in-memory
    steps:
      - checkout
      - solidusio_extensions/test-branch:
          branch: v2.8
      - store_test_results:
          path: test-results

  run-specs-2-7:
    executor: sqlite-in-memory
    steps:
      - checkout
      - solidusio_extensions/test-branch:
          branch: v2.7
      - store_test_results:
          path: test-results

workflows:
  "Run specs on supported Solidus versions":
    jobs:
      - run-specs-master
      - run-specs-2-9
      - run-specs-2-8
      - run-specs-2-7
  "Weekly run specs against master":
    triggers:
      - schedule:
          cron: "0 0 * * 4" # every Thursday
          filters:
            branches:
              only:
                - master
    jobs:
      - run-specs-master
      - run-specs-2-9
      - run-specs-2-8
      - run-specs-2-7
